import { Ride } from "@/src/types/global";

export const MOCK_RIDES: Ride[] = [
  // Tashkent to Regions
  {
    id: "1",
    driver: { id: "d1", name: "Abbos G.", rating: 4.8, reviewCount: 124, avatar: "" },
    from: "tashkent_city",
    to: "samarkand",
    date: "2026-03-20",
    departureTime: "08:30",
    price: 65000,
    availableSeats: 3,
    totalSeats: 4,
    carModel: "Chevrolet Gentra",
    carColor: "Black",
    rating: 4.8,
    reviewCount: 124
  },
  {
    id: "2",
    driver: { id: "d2", name: "Dilshod M.", rating: 4.9, reviewCount: 89, avatar: "" },
    from: "tashkent_city",
    to: "bukhara",
    date: "2026-03-20",
    departureTime: "09:15",
    price: 120000,
    availableSeats: 2,
    totalSeats: 4,
    carModel: "Chevrolet Malibu 2",
    carColor: "White",
    rating: 4.9,
    reviewCount: 89
  },
  {
    id: "3",
    driver: { id: "d3", name: "Jasur K.", rating: 4.7, reviewCount: 45, avatar: "" },
    from: "tashkent_city",
    to: "andijan",
    date: "2026-03-20",
    departureTime: "07:00",
    price: 95000,
    availableSeats: 4,
    totalSeats: 4,
    carModel: "Chevrolet Cobalt",
    carColor: "Silver",
    rating: 4.7,
    reviewCount: 45
  },
  {
    id: "4",
    driver: { id: "d4", name: "Sardor P.", rating: 4.6, reviewCount: 32, avatar: "" },
    from: "tashkent_city",
    to: "fergana",
    date: "2026-03-20",
    departureTime: "14:30",
    price: 85000,
    availableSeats: 1,
    totalSeats: 4,
    carModel: "Chevrolet Nexia 3",
    carColor: "White",
    rating: 4.6,
    reviewCount: 32
  },
  {
    id: "5",
    driver: { id: "d5", name: "Malika R.", rating: 5.0, reviewCount: 12, avatar: "" },
    from: "tashkent_city",
    to: "namangan",
    date: "2026-03-21",
    departureTime: "06:45",
    price: 90000,
    availableSeats: 3,
    totalSeats: 4,
    carModel: "Chevrolet Tracker",
    carColor: "Red",
    rating: 5.0,
    reviewCount: 12
  },
  {
    id: "6",
    driver: { id: "d6", name: "Rustam S.", rating: 4.5, reviewCount: 67, avatar: "" },
    from: "tashkent_city",
    to: "navoi",
    date: "2026-03-20",
    departureTime: "10:00",
    price: 80000,
    availableSeats: 4,
    totalSeats: 4,
    carModel: "Chevrolet Gentra",
    carColor: "Gray",
    rating: 4.5,
    reviewCount: 67
  },
  {
    id: "7",
    driver: { id: "d7", name: "Nozima T.", rating: 4.9, reviewCount: 156, avatar: "" },
    from: "tashkent_city",
    to: "jizzakh",
    date: "2026-03-20",
    departureTime: "11:30",
    price: 45000,
    availableSeats: 3,
    totalSeats: 4,
    carModel: "Chevrolet Cobalt",
    carColor: "Blue",
    rating: 4.9,
    reviewCount: 156
  },
  {
    id: "8",
    driver: { id: "d8", name: "Bekzod L.", rating: 4.7, reviewCount: 88, avatar: "" },
    from: "tashkent_city",
    to: "khorezm",
    date: "2026-03-22",
    departureTime: "18:00",
    price: 180000,
    availableSeats: 2,
    totalSeats: 4,
    carModel: "Chevrolet Malibu 2",
    carColor: "Black",
    rating: 4.7,
    reviewCount: 88
  },
  {
    id: "9",
    driver: { id: "d9", name: "Sarvar B.", rating: 4.3, reviewCount: 24, avatar: "" },
    from: "tashkent_city",
    to: "surkhandarya",
    date: "2026-03-20",
    departureTime: "19:30",
    price: 150000,
    availableSeats: 4,
    totalSeats: 4,
    carModel: "Chevrolet Gentra",
    carColor: "White",
    rating: 4.3,
    reviewCount: 24
  },
  {
    id: "10",
    driver: { id: "d10", name: "Aziz J.", rating: 4.8, reviewCount: 210, avatar: "" },
    from: "tashkent_city",
    to: "karakalpakstan",
    date: "2026-03-20",
    departureTime: "05:00",
    price: 200000,
    availableSeats: 1,
    totalSeats: 4,
    carModel: "Chevrolet Tracker",
    carColor: "White",
    rating: 4.8,
    reviewCount: 210
  },
  
  // Inter-region examples
  {
    id: "11",
    driver: { id: "d11", name: "Farrukh M.", rating: 4.7, reviewCount: 92, avatar: "" },
    from: "samarkand",
    to: "bukhara",
    date: "2026-03-20",
    departureTime: "08:00",
    price: 45000,
    availableSeats: 3,
    totalSeats: 4,
    carModel: "Chevrolet Nexia 3",
    carColor: "Silver",
    rating: 4.7,
    reviewCount: 92
  },
  {
    id: "12",
    driver: { id: "d12", name: "Otabek H.", rating: 4.4, reviewCount: 18, avatar: "" },
    from: "samarkand",
    to: "tashkent_city",
    date: "2026-03-20",
    departureTime: "15:00",
    price: 60000,
    availableSeats: 4,
    totalSeats: 4,
    carModel: "Chevrolet Gentra",
    carColor: "White",
    rating: 4.4,
    reviewCount: 18
  },
  {
    id: "13",
    driver: { id: "d13", name: "Zuhra A.", rating: 4.9, reviewCount: 42, avatar: "" },
    from: "fergana",
    to: "andijan",
    date: "2026-03-20",
    departureTime: "09:00",
    price: 25000,
    availableSeats: 2,
    totalSeats: 4,
    carModel: "Chevrolet Cobalt",
    carColor: "White",
    rating: 4.9,
    reviewCount: 42
  },
  {
    id: "14",
    driver: { id: "d14", name: "Sanjar T.", rating: 4.6, reviewCount: 55, avatar: "" },
    from: "andijan",
    to: "namangan",
    date: "2026-03-20",
    departureTime: "10:30",
    price: 30000,
    availableSeats: 3,
    totalSeats: 4,
    carModel: "Chevrolet Nexia 3",
    carColor: "Black",
    rating: 4.6,
    reviewCount: 55
  },
  {
    id: "15",
    driver: { id: "d15", name: "Javohir U.", rating: 4.8, reviewCount: 112, avatar: "" },
    from: "navoi",
    to: "samarkand",
    date: "2026-03-20",
    departureTime: "14:00",
    price: 35000,
    availableSeats: 4,
    totalSeats: 4,
    carModel: "Chevrolet Gentra",
    carColor: "Silver",
    rating: 4.8,
    reviewCount: 112
  },
  {
    id: "16",
    driver: { id: "d16", name: "Mansur B.", rating: 4.7, reviewCount: 38, avatar: "" },
    from: "khorezm",
    to: "bukhara",
    date: "2026-03-21",
    departureTime: "07:30",
    price: 70000,
    availableSeats: 3,
    totalSeats: 4,
    carModel: "Chevrolet Cobalt",
    carColor: "White",
    rating: 4.7,
    reviewCount: 38
  },
  {
    id: "17",
    driver: { id: "d17", name: "Sherzod K.", rating: 4.5, reviewCount: 29, avatar: "" },
    from: "kashkadarya",
    to: "surkhandarya",
    date: "2026-03-20",
    departureTime: "16:45",
    price: 55000,
    availableSeats: 2,
    totalSeats: 4,
    carModel: "Chevrolet Tracker",
    carColor: "Gray",
    rating: 4.5,
    reviewCount: 29
  },
  {
    id: "18",
    driver: { id: "d18", name: "Jamshid R.", rating: 4.9, reviewCount: 88, avatar: "" },
    from: "tashkent_city",
    to: "samarkand",
    date: "2026-03-20",
    departureTime: "13:20",
    price: 50000,
    availableSeats: 4,
    totalSeats: 4,
    carModel: "Chevrolet Cobalt",
    carColor: "White",
    rating: 4.9,
    reviewCount: 88
  },
  {
    id: "19",
    driver: { id: "d19", name: "Alisher F.", rating: 4.7, reviewCount: 64, avatar: "" },
    from: "tashkent_city",
    to: "samarkand",
    date: "2026-03-20",
    departureTime: "17:00",
    price: 75000,
    availableSeats: 1,
    totalSeats: 4,
    carModel: "Chevrolet Malibu 2",
    carColor: "Black",
    rating: 4.7,
    reviewCount: 64
  },
  {
    id: "20",
    driver: { id: "d20", name: "Nodira S.", rating: 5.0, reviewCount: 15, avatar: "" },
    from: "tashkent_city",
    to: "syrdarya",
    date: "2026-03-20",
    departureTime: "08:15",
    price: 35000,
    availableSeats: 3,
    totalSeats: 4,
    carModel: "Chevrolet Gentra",
    carColor: "White",
    rating: 5.0,
    reviewCount: 15
  },
  // Even more data covering all regions listed in regions.ts
  {
    id: "21",
    driver: { id: "d21", name: "Golib A.", rating: 4.6, reviewCount: 77, avatar: "" },
    from: "tashkent_city",
    to: "khorezm",
    date: "2026-03-20",
    departureTime: "20:00",
    price: 165000,
    availableSeats: 4,
    totalSeats: 4,
    carModel: "Chevrolet Malibu 2",
    carColor: "White",
    rating: 4.6,
    reviewCount: 77
  },
  {
    id: "22",
    driver: { id: "d22", name: "Umid V.", rating: 4.8, reviewCount: 142, avatar: "" },
    from: "tashkent_city",
    to: "kashkadarya",
    date: "2026-03-20",
    departureTime: "10:30",
    price: 85000,
    availableSeats: 2,
    totalSeats: 4,
    carModel: "Chevrolet Gentra",
    carColor: "Black",
    rating: 4.8,
    reviewCount: 142
  },
  {
    id: "23",
    driver: { id: "d23", name: "Lola K.", rating: 4.9, reviewCount: 58, avatar: "" },
    from: "tashkent_city",
    to: "tashkent_region",
    date: "2026-03-20",
    departureTime: "09:00",
    price: 20000,
    availableSeats: 3,
    totalSeats: 4,
    carModel: "Chevrolet Cobalt",
    carColor: "Gray",
    rating: 4.9,
    reviewCount: 58
  }
];
